In [1]:
import librosa
import matplotlib.pyplot as plt
import IPython.display as dis
import numpy as np
import os, sys
from tqdm import tqdm
import pandas as pd
import librosa.display

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
if not os.path.isdir('/content/melspectrogram_data'):
    os.makedirs('/content/melspectrogram_data')

In [4]:
!unzip /content/gdrive/MyDrive/final/melspectrogram_data_plus.zip -d /content/melspectrogram_data

Archive:  /content/gdrive/MyDrive/final/melspectrogram_data_plus.zip
  inflating: /content/melspectrogram_data/1002914.npy  
  inflating: /content/melspectrogram_data/10124.npy  
  inflating: /content/melspectrogram_data/101529890.npy  
  inflating: /content/melspectrogram_data/101545093.npy  
  inflating: /content/melspectrogram_data/1016369.npy  
  inflating: /content/melspectrogram_data/101678251.npy  
  inflating: /content/melspectrogram_data/101721111.npy  
  inflating: /content/melspectrogram_data/1017622.npy  
  inflating: /content/melspectrogram_data/1023889.npy  
  inflating: /content/melspectrogram_data/10291.npy  
  inflating: /content/melspectrogram_data/102979321.npy  
  inflating: /content/melspectrogram_data/104184.npy  
  inflating: /content/melspectrogram_data/105014.npy  
  inflating: /content/melspectrogram_data/105187.npy  
  inflating: /content/melspectrogram_data/1055513.npy  
  inflating: /content/melspectrogram_data/105699.npy  
  inflating: /content/melspectrog

In [ ]:
if not os.path.isdir('/content/mfcc_data'):
    os.makedirs('/content/mfcc_data')

In [ ]:
!unzip -o /content/gdrive/MyDrive/hindi/mfcc_data.zip -d /content/mfcc_data

In [5]:
rawdata = pd.read_csv('/content/gdrive/MyDrive/final/newtag_1118.csv')

In [15]:
lst = os.listdir('/content/melspectrogram_data')
lst[0]

'5663983.npy'

In [21]:
rawdata

Unnamed: 0         IDX      song_id            song_title  대분류       중분류
0              0     57088.0    4203068.0                    소녀  차분한       평온한
1              1    258244.0    4203787.0                   다알아   밝은       희망찬
2              2     57038.0    4209541.0           기억속의 먼 그대에게  우울한        슬픈
3              3    156375.0    4214654.0                  이별하면  우울한       외로운
4              4     56764.0    4230004.0    I'm Fine Thank You  우울한        슬픈
...          ...         ...          ...                   ...  ...       ...
3288        3288  20349965.0   34850634.0                사랑인가 봐   밝은   발랄한 희망찬
3289        3289  20350574.0   34890162.0              다시 만날까 봐  우울한    슬픈 외로운
3290        3290  20351090.0   34927767.0  정이라고 하자 (Feat. 10CM)  차분한  잔잔한 평온한 
3291        3291  20351312.0   34943312.0                나의 X에게   밝은       발랄한
3292        3292   5204263.0  101721111.0          On the Atlas  차분한  잔잔한 평온한 

[3293 rows x 6 columns]

In [23]:
lst = os.listdir('/content/melspectrogram_data')
data_x = []
data_y = []
errors = []
for i in tqdm(range(len(rawdata))):
    try:
        data_x.append(np.load('/content/melspectrogram_data/' + str(int(rawdata['song_id'].iloc[i]))+'.npy'))
        data_y.append(rawdata['대분류'].iloc[i])
    except:
        errors.append(str(int(rawdata['song_id'].iloc[i]))+'.npy')


100%|██████████| 3293/3293 [00:31<00:00, 105.78it/s]


In [26]:
len(data_y)

3253

In [ ]:
rawdata.iloc[111]

Unnamed: 0         149
song_id       30829905
new_tag            신나는
Name: 111, dtype: object

In [27]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
data_y = label_encoder.fit_transform(data_y)

In [28]:
wav_to_img_data = []
target = []

# 128*128 사이즈로 멜스펙토그램 이미지를 잘라서 담아두고
# 타겟값을 같이 추가한 넘파이배열을 만든다
for idx in tqdm(range(len(data_x))):
    for i in range(20):
        if 128 * (i+1) > len(data_x[idx][0]):
            break
        wav_to_img_data.append(data_x[idx][:, 128* i : 128 * (i+1)].reshape(128,-1,1))
        target.append(data_y[idx])
wav_to_img_data = np.array(wav_to_img_data)
target = np.array(target)

100%|██████████| 3253/3253 [00:00<00:00, 32803.53it/s]


In [29]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Dense, Input, BatchNormalization, Activation, Flatten

def VGG_model():
    
    inputs = Input(shape=(128,128,1))
    x = Conv2D(64,3, padding='same')(inputs)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(64,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = MaxPooling2D(2)(x)
    
    x = Conv2D(128,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(128,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = MaxPooling2D(2)(x)
    
    x = Conv2D(256,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(256,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(256,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = MaxPooling2D(2)(x)
    
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = MaxPooling2D(2)(x)
    
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = MaxPooling2D(2)(x)
    
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = MaxPooling2D(2)(x)
    
    x = Flatten()(x)
    x = Dense(1024, activation='relu')(x)
    x = Dropout(0.5)(x)
    x = Dense(1024, activation='relu')(x)
    x = Dropout(0.5)(x)
    x = Dense(6, activation='softmax')(x)
    
    return tf.keras.Model(inputs, x)

In [30]:
model = VGG_model()

In [ ]:
model.summary()

In [31]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=5e-5), loss='sparse_categorical_crossentropy',  metrics=['acc'])

In [ ]:
history = model.fit(wav_to_img_data, target, epochs=10, batch_size=32, validation_split=0.2)

In [157]:
model.save('/content/gdrive/MyDrive/final/vgg_1118.h5')

### 추론

In [37]:
test_data = pd.read_csv('/content/gdrive/MyDrive/final/test_newtag_1118.csv')

test_x = []
test_y = []
for i in tqdm(range(len(test_data))):
    try:
        test_x.append(np.load('/content/melspectrogram_data/' + str(int(test_data['song_id'].iloc[i]))+'.npy'))
        test_y.append(test_data['대분류'].iloc[i])
    except:
        pass

100%|██████████| 480/480 [00:12<00:00, 38.82it/s]


In [38]:
test_y = label_encoder.fit_transform(test_y)

In [158]:
test_whole = []
for i in range(len(test_x)):
    one_sample = []
    for j in range(len(test_x[i][0])):
        if 32*j+128 >= len(test_x[i][0]):
            break
        one_sample.append(test_x[i][:, 32*j : 32*j+128].reshape(128,128,-1))
    test_whole.append(one_sample)

In [159]:
cnt = 0
correct = 0
total_result = []
co_lst = []

for i in tqdm(range(len(test_whole))):
    infer = model.predict(np.array(test_whole[i]))
    infer = np.argmax(infer, axis=1)
    count_ = np.unique(infer, return_counts=True)
    total_result.append(count_)
    result = count_[0][np.argmax(count_[1])]
    cnt += 1
    # print(count_)
    # print(result, test_y[i])
    if result == test_y[i]:
        co_lst.append(i)
        correct += 1

  0%|          | 0/480 [00:00<?, ?it/s]

11/11 [==============================] - 1s 59ms/step


  0%|          | 1/480 [00:00<05:21,  1.49it/s]

14/14 [==============================] - 1s 50ms/step


  0%|          | 2/480 [00:01<05:36,  1.42it/s]

11/11 [==============================] - 1s 51ms/step


  1%|          | 3/480 [00:02<05:13,  1.52it/s]

11/11 [==============================] - 1s 51ms/step


  1%|          | 4/480 [00:02<05:05,  1.56it/s]

8/8 [==============================] - 0s 51ms/step


  1%|          | 5/480 [00:03<04:32,  1.74it/s]

10/10 [==============================] - 0s 51ms/step


  1%|▏         | 6/480 [00:03<04:28,  1.76it/s]

10/10 [==============================] - 0s 50ms/step


  1%|▏         | 7/480 [00:04<04:25,  1.78it/s]

10/10 [==============================] - 0s 50ms/step


  2%|▏         | 8/480 [00:04<04:19,  1.82it/s]

11/11 [==============================] - 1s 51ms/step


  2%|▏         | 9/480 [00:05<04:27,  1.76it/s]

11/11 [==============================] - 1s 50ms/step


  2%|▏         | 10/480 [00:05<04:27,  1.75it/s]

11/11 [==============================] - 1s 51ms/step


  2%|▏         | 11/480 [00:06<04:29,  1.74it/s]

12/12 [==============================] - 1s 51ms/step


  2%|▎         | 12/480 [00:07<04:42,  1.65it/s]

10/10 [==============================] - 0s 51ms/step


  3%|▎         | 13/480 [00:07<04:35,  1.69it/s]

10/10 [==============================] - 0s 51ms/step


  3%|▎         | 14/480 [00:08<04:32,  1.71it/s]

11/11 [==============================] - 1s 51ms/step


  3%|▎         | 15/480 [00:08<04:38,  1.67it/s]

12/12 [==============================] - 1s 51ms/step


  3%|▎         | 16/480 [00:09<04:45,  1.62it/s]

11/11 [==============================] - 1s 51ms/step


  4%|▎         | 17/480 [00:10<04:44,  1.63it/s]

3/3 [==============================] - 0s 49ms/step


  4%|▍         | 18/480 [00:10<03:44,  2.06it/s]

11/11 [==============================] - 1s 51ms/step


  4%|▍         | 19/480 [00:10<03:57,  1.94it/s]

11/11 [==============================] - 1s 51ms/step


  4%|▍         | 20/480 [00:11<04:10,  1.84it/s]

12/12 [==============================] - 1s 51ms/step


  4%|▍         | 21/480 [00:12<04:23,  1.74it/s]

9/9 [==============================] - 0s 51ms/step


  5%|▍         | 22/480 [00:12<04:11,  1.82it/s]

11/11 [==============================] - 1s 51ms/step


  5%|▍         | 23/480 [00:13<04:18,  1.77it/s]

8/8 [==============================] - 0s 50ms/step


  5%|▌         | 24/480 [00:13<04:01,  1.88it/s]

14/14 [==============================] - 1s 51ms/step


  5%|▌         | 25/480 [00:14<04:33,  1.66it/s]

10/10 [==============================] - 0s 51ms/step


  5%|▌         | 26/480 [00:15<04:23,  1.73it/s]

12/12 [==============================] - 1s 51ms/step


  6%|▌         | 27/480 [00:15<04:33,  1.65it/s]

12/12 [==============================] - 1s 51ms/step


  6%|▌         | 28/480 [00:16<04:37,  1.63it/s]

12/12 [==============================] - 1s 51ms/step


  6%|▌         | 29/480 [00:16<04:40,  1.61it/s]

10/10 [==============================] - 0s 51ms/step


  6%|▋         | 30/480 [00:17<04:31,  1.66it/s]

10/10 [==============================] - 0s 51ms/step


  6%|▋         | 31/480 [00:18<04:24,  1.70it/s]

12/12 [==============================] - 1s 50ms/step


  7%|▋         | 32/480 [00:18<04:28,  1.67it/s]

11/11 [==============================] - 1s 51ms/step


  7%|▋         | 33/480 [00:19<04:30,  1.66it/s]

10/10 [==============================] - 0s 51ms/step


  7%|▋         | 34/480 [00:19<04:20,  1.71it/s]

10/10 [==============================] - 0s 51ms/step


  7%|▋         | 35/480 [00:20<04:13,  1.75it/s]

10/10 [==============================] - 0s 51ms/step


  8%|▊         | 36/480 [00:20<04:09,  1.78it/s]

13/13 [==============================] - 1s 51ms/step


  8%|▊         | 37/480 [00:21<04:29,  1.64it/s]

11/11 [==============================] - 1s 51ms/step


  8%|▊         | 38/480 [00:22<04:25,  1.66it/s]

12/12 [==============================] - 1s 51ms/step


  8%|▊         | 39/480 [00:22<04:31,  1.63it/s]

11/11 [==============================] - 1s 51ms/step


  8%|▊         | 40/480 [00:23<04:30,  1.62it/s]

12/12 [==============================] - 1s 51ms/step


  9%|▊         | 41/480 [00:24<04:31,  1.62it/s]

9/9 [==============================] - 0s 51ms/step


  9%|▉         | 42/480 [00:24<04:13,  1.73it/s]

11/11 [==============================] - 1s 51ms/step


  9%|▉         | 43/480 [00:25<04:13,  1.72it/s]

13/13 [==============================] - 1s 51ms/step


  9%|▉         | 44/480 [00:25<04:28,  1.62it/s]

10/10 [==============================] - 0s 51ms/step


  9%|▉         | 45/480 [00:26<04:19,  1.68it/s]

12/12 [==============================] - 1s 51ms/step


 10%|▉         | 46/480 [00:27<04:25,  1.64it/s]

12/12 [==============================] - 1s 51ms/step


 10%|▉         | 47/480 [00:27<04:31,  1.59it/s]

10/10 [==============================] - 0s 51ms/step


 10%|█         | 48/480 [00:28<04:18,  1.67it/s]

12/12 [==============================] - 1s 51ms/step


 10%|█         | 49/480 [00:28<04:23,  1.64it/s]

13/13 [==============================] - 1s 51ms/step


 10%|█         | 50/480 [00:29<04:37,  1.55it/s]

17/17 [==============================] - 1s 51ms/step


 11%|█         | 51/480 [00:30<05:15,  1.36it/s]

9/9 [==============================] - 0s 51ms/step


 11%|█         | 52/480 [00:31<04:45,  1.50it/s]

12/12 [==============================] - 1s 51ms/step


 11%|█         | 53/480 [00:31<04:45,  1.49it/s]

11/11 [==============================] - 1s 51ms/step


 11%|█▏        | 54/480 [00:32<04:34,  1.55it/s]

16/16 [==============================] - 1s 52ms/step


 11%|█▏        | 55/480 [00:33<05:03,  1.40it/s]

17/17 [==============================] - 1s 52ms/step


 12%|█▏        | 56/480 [00:34<05:32,  1.28it/s]

11/11 [==============================] - 1s 52ms/step


 12%|█▏        | 57/480 [00:34<05:06,  1.38it/s]

13/13 [==============================] - 1s 52ms/step


 12%|█▏        | 58/480 [00:35<05:06,  1.38it/s]

13/13 [==============================] - 1s 51ms/step


 12%|█▏        | 59/480 [00:36<05:04,  1.38it/s]

13/13 [==============================] - 1s 51ms/step


 12%|█▎        | 60/480 [00:36<05:03,  1.38it/s]

6/6 [==============================] - 0s 50ms/step


 13%|█▎        | 61/480 [00:37<04:13,  1.65it/s]

11/11 [==============================] - 1s 51ms/step


 13%|█▎        | 62/480 [00:37<04:14,  1.64it/s]

12/12 [==============================] - 1s 51ms/step


 13%|█▎        | 63/480 [00:38<04:17,  1.62it/s]

12/12 [==============================] - 1s 51ms/step


 13%|█▎        | 64/480 [00:39<04:24,  1.58it/s]

11/11 [==============================] - 1s 52ms/step


 14%|█▎        | 65/480 [00:39<04:19,  1.60it/s]

13/13 [==============================] - 1s 51ms/step


 14%|█▍        | 66/480 [00:40<04:30,  1.53it/s]

12/12 [==============================] - 1s 52ms/step


 14%|█▍        | 67/480 [00:41<04:29,  1.53it/s]

10/10 [==============================] - 0s 52ms/step


 14%|█▍        | 68/480 [00:41<04:18,  1.59it/s]

13/13 [==============================] - 1s 51ms/step


 14%|█▍        | 69/480 [00:42<04:27,  1.53it/s]

11/11 [==============================] - 1s 51ms/step


 15%|█▍        | 70/480 [00:43<04:23,  1.56it/s]

11/11 [==============================] - 1s 52ms/step


 15%|█▍        | 71/480 [00:43<04:17,  1.59it/s]

8/8 [==============================] - 0s 52ms/step


 15%|█▌        | 72/480 [00:44<03:56,  1.72it/s]

3/3 [==============================] - 0s 49ms/step


 15%|█▌        | 73/480 [00:44<03:04,  2.21it/s]

14/14 [==============================] - 1s 52ms/step


 15%|█▌        | 74/480 [00:45<03:39,  1.85it/s]

9/9 [==============================] - 0s 52ms/step


 16%|█▌        | 75/480 [00:45<03:35,  1.88it/s]

9/9 [==============================] - 0s 52ms/step


 16%|█▌        | 76/480 [00:46<03:31,  1.91it/s]

10/10 [==============================] - 0s 52ms/step


 16%|█▌        | 77/480 [00:46<03:37,  1.86it/s]

12/12 [==============================] - 1s 52ms/step


 16%|█▋        | 78/480 [00:47<03:53,  1.72it/s]

11/11 [==============================] - 1s 52ms/step


 16%|█▋        | 79/480 [00:47<03:54,  1.71it/s]

10/10 [==============================] - 0s 52ms/step


 17%|█▋        | 80/480 [00:48<03:51,  1.73it/s]

10/10 [==============================] - 0s 52ms/step


 17%|█▋        | 81/480 [00:49<03:46,  1.76it/s]

9/9 [==============================] - 0s 52ms/step


 17%|█▋        | 82/480 [00:49<03:37,  1.83it/s]

11/11 [==============================] - 1s 53ms/step


 17%|█▋        | 83/480 [00:50<03:43,  1.78it/s]

2/2 [==============================] - 0s 46ms/step


 18%|█▊        | 84/480 [00:50<02:52,  2.29it/s]

11/11 [==============================] - 1s 52ms/step


 18%|█▊        | 85/480 [00:50<03:14,  2.03it/s]

14/14 [==============================] - 1s 52ms/step


 18%|█▊        | 86/480 [00:51<03:50,  1.71it/s]

12/12 [==============================] - 1s 52ms/step


 18%|█▊        | 87/480 [00:52<04:01,  1.63it/s]

13/13 [==============================] - 1s 52ms/step


 18%|█▊        | 88/480 [00:53<04:10,  1.56it/s]

12/12 [==============================] - 1s 51ms/step


 19%|█▊        | 89/480 [00:53<04:11,  1.55it/s]

12/12 [==============================] - 1s 52ms/step


 19%|█▉        | 90/480 [00:54<04:11,  1.55it/s]

10/10 [==============================] - 0s 52ms/step


 19%|█▉        | 91/480 [00:54<04:00,  1.61it/s]

9/9 [==============================] - 0s 52ms/step


 19%|█▉        | 92/480 [00:55<03:44,  1.73it/s]

11/11 [==============================] - 1s 52ms/step


 19%|█▉        | 93/480 [00:56<03:49,  1.69it/s]

9/9 [==============================] - 0s 51ms/step


 20%|█▉        | 94/480 [00:56<03:36,  1.78it/s]

12/12 [==============================] - 1s 52ms/step


 20%|█▉        | 95/480 [00:57<03:46,  1.70it/s]

10/10 [==============================] - 0s 52ms/step


 20%|██        | 96/480 [00:57<03:43,  1.71it/s]

21/21 [==============================] - 1s 53ms/step


 20%|██        | 97/480 [00:58<04:54,  1.30it/s]

11/11 [==============================] - 1s 52ms/step


 20%|██        | 98/480 [00:59<04:36,  1.38it/s]

11/11 [==============================] - 1s 52ms/step


 21%|██        | 99/480 [01:00<04:23,  1.45it/s]

11/11 [==============================] - 1s 52ms/step


 21%|██        | 100/480 [01:00<04:12,  1.51it/s]

14/14 [==============================] - 1s 52ms/step


 21%|██        | 101/480 [01:01<04:24,  1.43it/s]

11/11 [==============================] - 1s 52ms/step


 21%|██▏       | 102/480 [01:02<04:15,  1.48it/s]

13/13 [==============================] - 1s 52ms/step


 21%|██▏       | 103/480 [01:02<04:18,  1.46it/s]

11/11 [==============================] - 1s 52ms/step


 22%|██▏       | 104/480 [01:03<04:11,  1.50it/s]

12/12 [==============================] - 1s 52ms/step


 22%|██▏       | 105/480 [01:04<04:08,  1.51it/s]

10/10 [==============================] - 0s 52ms/step


 22%|██▏       | 106/480 [01:04<03:54,  1.59it/s]

10/10 [==============================] - 0s 52ms/step


 22%|██▏       | 107/480 [01:05<03:50,  1.62it/s]

9/9 [==============================] - 0s 52ms/step


 22%|██▎       | 108/480 [01:05<03:35,  1.72it/s]

10/10 [==============================] - 0s 52ms/step


 23%|██▎       | 109/480 [01:06<03:34,  1.73it/s]

11/11 [==============================] - 1s 52ms/step


 23%|██▎       | 110/480 [01:07<03:40,  1.68it/s]

12/12 [==============================] - 1s 53ms/step


 23%|██▎       | 111/480 [01:07<03:49,  1.61it/s]

10/10 [==============================] - 0s 53ms/step


 23%|██▎       | 112/480 [01:08<03:41,  1.66it/s]

10/10 [==============================] - 0s 52ms/step


 24%|██▎       | 113/480 [01:08<03:34,  1.71it/s]

10/10 [==============================] - 0s 52ms/step


 24%|██▍       | 114/480 [01:09<03:33,  1.72it/s]

12/12 [==============================] - 1s 53ms/step


 24%|██▍       | 115/480 [01:10<03:43,  1.63it/s]

8/8 [==============================] - 0s 51ms/step


 24%|██▍       | 116/480 [01:10<03:23,  1.79it/s]

9/9 [==============================] - 0s 52ms/step


 24%|██▍       | 117/480 [01:11<03:18,  1.83it/s]

9/9 [==============================] - 0s 53ms/step


 25%|██▍       | 118/480 [01:11<03:16,  1.84it/s]

11/11 [==============================] - 1s 52ms/step


 25%|██▍       | 119/480 [01:12<03:21,  1.79it/s]

9/9 [==============================] - 0s 53ms/step


 25%|██▌       | 120/480 [01:12<03:15,  1.84it/s]

12/12 [==============================] - 1s 52ms/step


 25%|██▌       | 121/480 [01:13<03:25,  1.75it/s]

10/10 [==============================] - 0s 52ms/step


 25%|██▌       | 122/480 [01:13<03:25,  1.74it/s]

7/7 [==============================] - 0s 53ms/step


 26%|██▌       | 123/480 [01:14<03:08,  1.89it/s]

10/10 [==============================] - 0s 52ms/step


 26%|██▌       | 124/480 [01:14<03:14,  1.83it/s]

6/6 [==============================] - 0s 52ms/step


 26%|██▌       | 125/480 [01:15<02:53,  2.05it/s]

14/14 [==============================] - 1s 53ms/step


 26%|██▋       | 126/480 [01:16<03:25,  1.72it/s]

11/11 [==============================] - 1s 53ms/step


 26%|██▋       | 127/480 [01:16<03:29,  1.68it/s]

10/10 [==============================] - 0s 53ms/step


 27%|██▋       | 128/480 [01:17<03:27,  1.70it/s]

12/12 [==============================] - 1s 53ms/step


 27%|██▋       | 129/480 [01:17<03:35,  1.63it/s]

11/11 [==============================] - 1s 52ms/step


 27%|██▋       | 130/480 [01:18<03:35,  1.62it/s]

8/8 [==============================] - 0s 53ms/step


 27%|██▋       | 131/480 [01:18<03:19,  1.75it/s]

11/11 [==============================] - 1s 52ms/step


 28%|██▊       | 132/480 [01:19<03:22,  1.72it/s]

15/15 [==============================] - 1s 53ms/step


 28%|██▊       | 133/480 [01:20<03:48,  1.52it/s]

11/11 [==============================] - 1s 53ms/step


 28%|██▊       | 134/480 [01:21<03:41,  1.56it/s]

11/11 [==============================] - 1s 53ms/step


 28%|██▊       | 135/480 [01:21<03:40,  1.56it/s]

15/15 [==============================] - 1s 54ms/step


 28%|██▊       | 136/480 [01:22<03:59,  1.43it/s]

11/11 [==============================] - 1s 52ms/step


 29%|██▊       | 137/480 [01:23<03:49,  1.50it/s]

12/12 [==============================] - 1s 53ms/step


 29%|██▉       | 138/480 [01:23<03:50,  1.48it/s]

11/11 [==============================] - 1s 53ms/step


 29%|██▉       | 139/480 [01:24<03:44,  1.52it/s]

10/10 [==============================] - 0s 53ms/step


 29%|██▉       | 140/480 [01:24<03:34,  1.59it/s]

9/9 [==============================] - 0s 54ms/step


 29%|██▉       | 141/480 [01:25<03:24,  1.66it/s]

15/15 [==============================] - 1s 53ms/step


 30%|██▉       | 142/480 [01:26<03:49,  1.47it/s]

11/11 [==============================] - 1s 53ms/step


 30%|██▉       | 143/480 [01:26<03:42,  1.51it/s]

10/10 [==============================] - 1s 54ms/step


 30%|███       | 144/480 [01:27<03:32,  1.58it/s]

12/12 [==============================] - 1s 53ms/step


 30%|███       | 145/480 [01:28<03:35,  1.56it/s]

7/7 [==============================] - 0s 53ms/step


 30%|███       | 146/480 [01:28<03:10,  1.75it/s]

10/10 [==============================] - 0s 53ms/step


 31%|███       | 147/480 [01:29<03:12,  1.73it/s]

10/10 [==============================] - 1s 54ms/step


 31%|███       | 148/480 [01:29<03:12,  1.73it/s]

11/11 [==============================] - 1s 54ms/step


 31%|███       | 149/480 [01:30<03:19,  1.66it/s]

9/9 [==============================] - 0s 54ms/step


 31%|███▏      | 150/480 [01:30<03:10,  1.73it/s]

10/10 [==============================] - 0s 53ms/step


 31%|███▏      | 151/480 [01:31<03:10,  1.73it/s]

8/8 [==============================] - 0s 54ms/step


 32%|███▏      | 152/480 [01:32<03:00,  1.82it/s]

6/6 [==============================] - 0s 52ms/step


 32%|███▏      | 153/480 [01:32<02:37,  2.07it/s]

9/9 [==============================] - 0s 53ms/step


 32%|███▏      | 154/480 [01:32<02:41,  2.02it/s]

9/9 [==============================] - 0s 54ms/step


 32%|███▏      | 155/480 [01:33<02:43,  1.99it/s]

14/14 [==============================] - 1s 53ms/step


 32%|███▎      | 156/480 [01:34<03:12,  1.68it/s]

13/13 [==============================] - 1s 53ms/step


 33%|███▎      | 157/480 [01:34<03:24,  1.58it/s]

12/12 [==============================] - 1s 53ms/step


 33%|███▎      | 158/480 [01:35<03:30,  1.53it/s]

4/4 [==============================] - 0s 51ms/step


 33%|███▎      | 159/480 [01:35<02:50,  1.88it/s]

15/15 [==============================] - 1s 53ms/step


 33%|███▎      | 160/480 [01:36<03:22,  1.58it/s]

11/11 [==============================] - 1s 53ms/step


 34%|███▎      | 161/480 [01:37<03:22,  1.57it/s]

10/10 [==============================] - 1s 54ms/step


 34%|███▍      | 162/480 [01:37<03:16,  1.62it/s]

12/12 [==============================] - 1s 54ms/step


 34%|███▍      | 163/480 [01:38<03:20,  1.58it/s]

10/10 [==============================] - 0s 53ms/step


 34%|███▍      | 164/480 [01:39<03:13,  1.64it/s]

9/9 [==============================] - 0s 54ms/step


 34%|███▍      | 165/480 [01:39<03:06,  1.69it/s]

9/9 [==============================] - 0s 54ms/step


 35%|███▍      | 166/480 [01:40<02:58,  1.76it/s]

11/11 [==============================] - 1s 54ms/step


 35%|███▍      | 167/480 [01:40<03:05,  1.69it/s]

10/10 [==============================] - 0s 53ms/step


 35%|███▌      | 168/480 [01:41<03:04,  1.69it/s]

2/2 [==============================] - 0s 45ms/step


 35%|███▌      | 169/480 [01:41<02:18,  2.25it/s]

12/12 [==============================] - 1s 53ms/step


 35%|███▌      | 170/480 [01:42<02:38,  1.95it/s]

13/13 [==============================] - 1s 54ms/step


 36%|███▌      | 171/480 [01:43<02:58,  1.73it/s]

10/10 [==============================] - 0s 53ms/step


 36%|███▌      | 172/480 [01:43<02:56,  1.74it/s]

12/12 [==============================] - 1s 54ms/step


 36%|███▌      | 173/480 [01:44<03:07,  1.63it/s]

9/9 [==============================] - 0s 54ms/step


 36%|███▋      | 174/480 [01:44<03:00,  1.69it/s]

11/11 [==============================] - 1s 53ms/step


 36%|███▋      | 175/480 [01:45<03:03,  1.66it/s]

10/10 [==============================] - 1s 54ms/step


 37%|███▋      | 176/480 [01:46<03:02,  1.67it/s]

11/11 [==============================] - 1s 54ms/step


 37%|███▋      | 177/480 [01:46<03:03,  1.65it/s]

10/10 [==============================] - 0s 53ms/step


 37%|███▋      | 178/480 [01:47<03:01,  1.66it/s]

9/9 [==============================] - 0s 54ms/step


 37%|███▋      | 179/480 [01:47<02:55,  1.72it/s]

11/11 [==============================] - 1s 53ms/step


 38%|███▊      | 180/480 [01:48<02:57,  1.69it/s]

9/9 [==============================] - 0s 53ms/step


 38%|███▊      | 181/480 [01:48<02:51,  1.75it/s]

12/12 [==============================] - 1s 53ms/step


 38%|███▊      | 182/480 [01:49<02:59,  1.66it/s]

12/12 [==============================] - 1s 54ms/step


 38%|███▊      | 183/480 [01:50<03:07,  1.58it/s]

17/17 [==============================] - 1s 54ms/step


 38%|███▊      | 184/480 [01:51<03:37,  1.36it/s]

15/15 [==============================] - 1s 53ms/step


 39%|███▊      | 185/480 [01:52<03:47,  1.30it/s]

13/13 [==============================] - 1s 54ms/step


 39%|███▉      | 186/480 [01:52<03:44,  1.31it/s]

12/12 [==============================] - 1s 53ms/step


 39%|███▉      | 187/480 [01:53<03:34,  1.37it/s]

9/9 [==============================] - 0s 54ms/step


 39%|███▉      | 188/480 [01:54<03:15,  1.50it/s]

10/10 [==============================] - 1s 54ms/step


 39%|███▉      | 189/480 [01:54<03:08,  1.55it/s]

11/11 [==============================] - 1s 53ms/step


 40%|███▉      | 190/480 [01:55<03:03,  1.58it/s]

7/7 [==============================] - 0s 53ms/step


 40%|███▉      | 191/480 [01:55<02:44,  1.75it/s]

9/9 [==============================] - 0s 53ms/step


 40%|████      | 192/480 [01:56<02:41,  1.79it/s]

12/12 [==============================] - 1s 54ms/step


 40%|████      | 193/480 [01:56<02:50,  1.69it/s]

11/11 [==============================] - 1s 53ms/step


 40%|████      | 194/480 [01:57<02:53,  1.65it/s]

10/10 [==============================] - 0s 53ms/step


 41%|████      | 195/480 [01:58<02:51,  1.67it/s]

13/13 [==============================] - 1s 53ms/step


 41%|████      | 196/480 [01:58<02:59,  1.58it/s]

11/11 [==============================] - 1s 53ms/step


 41%|████      | 197/480 [01:59<02:57,  1.60it/s]

10/10 [==============================] - 0s 53ms/step


 41%|████▏     | 198/480 [02:00<02:52,  1.64it/s]

12/12 [==============================] - 1s 53ms/step


 41%|████▏     | 199/480 [02:00<02:57,  1.59it/s]

10/10 [==============================] - 1s 54ms/step


 42%|████▏     | 200/480 [02:01<02:51,  1.63it/s]

8/8 [==============================] - 0s 54ms/step


 42%|████▏     | 201/480 [02:01<02:38,  1.76it/s]

8/8 [==============================] - 0s 53ms/step


 42%|████▏     | 202/480 [02:02<02:27,  1.89it/s]

8/8 [==============================] - 0s 53ms/step


 42%|████▏     | 203/480 [02:02<02:19,  1.99it/s]

10/10 [==============================] - 1s 54ms/step


 42%|████▎     | 204/480 [02:03<02:26,  1.89it/s]

14/14 [==============================] - 1s 53ms/step


 43%|████▎     | 205/480 [02:03<02:48,  1.63it/s]

13/13 [==============================] - 1s 54ms/step


 43%|████▎     | 206/480 [02:04<02:59,  1.53it/s]

9/9 [==============================] - 0s 54ms/step


 43%|████▎     | 207/480 [02:05<02:47,  1.63it/s]

10/10 [==============================] - 0s 53ms/step


 43%|████▎     | 208/480 [02:05<02:44,  1.66it/s]

10/10 [==============================] - 1s 54ms/step


 44%|████▎     | 209/480 [02:06<02:43,  1.65it/s]

21/21 [==============================] - 1s 56ms/step


 44%|████▍     | 210/480 [02:07<03:34,  1.26it/s]

12/12 [==============================] - 1s 53ms/step


 44%|████▍     | 211/480 [02:08<03:25,  1.31it/s]

9/9 [==============================] - 0s 55ms/step


 44%|████▍     | 212/480 [02:08<03:06,  1.44it/s]

10/10 [==============================] - 1s 55ms/step


 44%|████▍     | 213/480 [02:09<02:57,  1.50it/s]

10/10 [==============================] - 1s 55ms/step


 45%|████▍     | 214/480 [02:10<02:52,  1.55it/s]

14/14 [==============================] - 1s 54ms/step


 45%|████▍     | 215/480 [02:10<03:05,  1.43it/s]

8/8 [==============================] - 0s 55ms/step


 45%|████▌     | 216/480 [02:11<02:48,  1.57it/s]

9/9 [==============================] - 0s 55ms/step


 45%|████▌     | 217/480 [02:11<02:40,  1.64it/s]

10/10 [==============================] - 0s 53ms/step


 45%|████▌     | 218/480 [02:12<02:37,  1.66it/s]

11/11 [==============================] - 1s 54ms/step


 46%|████▌     | 219/480 [02:13<02:40,  1.62it/s]

16/16 [==============================] - 1s 55ms/step


 46%|████▌     | 220/480 [02:14<03:05,  1.41it/s]

11/11 [==============================] - 1s 54ms/step


 46%|████▌     | 221/480 [02:14<02:58,  1.45it/s]

9/9 [==============================] - 0s 55ms/step


 46%|████▋     | 222/480 [02:15<02:47,  1.54it/s]

10/10 [==============================] - 1s 56ms/step


 46%|████▋     | 223/480 [02:15<02:43,  1.57it/s]

8/8 [==============================] - 0s 55ms/step


 47%|████▋     | 224/480 [02:16<02:31,  1.69it/s]

11/11 [==============================] - 1s 55ms/step


 47%|████▋     | 225/480 [02:17<02:34,  1.66it/s]

9/9 [==============================] - 0s 55ms/step


 47%|████▋     | 226/480 [02:17<02:27,  1.73it/s]

9/9 [==============================] - 0s 56ms/step


 47%|████▋     | 227/480 [02:18<02:24,  1.76it/s]

10/10 [==============================] - 1s 56ms/step


 48%|████▊     | 228/480 [02:18<02:24,  1.74it/s]

10/10 [==============================] - 1s 57ms/step


 48%|████▊     | 229/480 [02:19<02:27,  1.71it/s]

10/10 [==============================] - 1s 56ms/step


 48%|████▊     | 230/480 [02:19<02:26,  1.71it/s]

10/10 [==============================] - 1s 55ms/step


 48%|████▊     | 231/480 [02:20<02:27,  1.69it/s]

11/11 [==============================] - 1s 56ms/step


 48%|████▊     | 232/480 [02:21<02:32,  1.62it/s]

13/13 [==============================] - 1s 56ms/step


 49%|████▊     | 233/480 [02:21<02:43,  1.51it/s]

11/11 [==============================] - 1s 57ms/step


 49%|████▉     | 234/480 [02:22<02:41,  1.52it/s]

10/10 [==============================] - 1s 56ms/step


 49%|████▉     | 235/480 [02:23<02:37,  1.56it/s]

9/9 [==============================] - 0s 56ms/step


 49%|████▉     | 236/480 [02:23<02:29,  1.63it/s]

11/11 [==============================] - 1s 56ms/step


 49%|████▉     | 237/480 [02:24<02:32,  1.59it/s]

10/10 [==============================] - 1s 55ms/step


 50%|████▉     | 238/480 [02:24<02:28,  1.63it/s]

10/10 [==============================] - 1s 56ms/step


 50%|████▉     | 239/480 [02:25<02:26,  1.65it/s]

10/10 [==============================] - 1s 57ms/step


 50%|█████     | 240/480 [02:26<02:24,  1.66it/s]

12/12 [==============================] - 1s 55ms/step


 50%|█████     | 241/480 [02:26<02:30,  1.59it/s]

10/10 [==============================] - 1s 56ms/step


 50%|█████     | 242/480 [02:27<02:28,  1.60it/s]

11/11 [==============================] - 1s 55ms/step


 51%|█████     | 243/480 [02:28<02:29,  1.59it/s]

8/8 [==============================] - 0s 56ms/step


 51%|█████     | 244/480 [02:28<02:18,  1.70it/s]

7/7 [==============================] - 0s 54ms/step


 51%|█████     | 245/480 [02:29<02:06,  1.85it/s]

9/9 [==============================] - 0s 55ms/step


 51%|█████▏    | 246/480 [02:29<02:04,  1.89it/s]

11/11 [==============================] - 1s 55ms/step


 51%|█████▏    | 247/480 [02:30<02:12,  1.76it/s]

17/17 [==============================] - 1s 56ms/step


 52%|█████▏    | 248/480 [02:31<02:42,  1.43it/s]

11/11 [==============================] - 1s 55ms/step


 52%|█████▏    | 249/480 [02:31<02:37,  1.47it/s]

9/9 [==============================] - 0s 55ms/step


 52%|█████▏    | 250/480 [02:32<02:27,  1.56it/s]

10/10 [==============================] - 1s 57ms/step


 52%|█████▏    | 251/480 [02:32<02:22,  1.61it/s]

11/11 [==============================] - 1s 54ms/step


 52%|█████▎    | 252/480 [02:33<02:21,  1.61it/s]

10/10 [==============================] - 1s 55ms/step


 53%|█████▎    | 253/480 [02:34<02:17,  1.65it/s]

9/9 [==============================] - 0s 56ms/step


 53%|█████▎    | 254/480 [02:34<02:11,  1.72it/s]

13/13 [==============================] - 1s 55ms/step


 53%|█████▎    | 255/480 [02:35<02:21,  1.59it/s]

12/12 [==============================] - 1s 55ms/step


 53%|█████▎    | 256/480 [02:36<02:24,  1.55it/s]

10/10 [==============================] - 1s 56ms/step


 54%|█████▎    | 257/480 [02:36<02:21,  1.58it/s]

11/11 [==============================] - 1s 55ms/step


 54%|█████▍    | 258/480 [02:37<02:21,  1.57it/s]

12/12 [==============================] - 1s 55ms/step


 54%|█████▍    | 259/480 [02:38<02:26,  1.51it/s]

11/11 [==============================] - 1s 56ms/step


 54%|█████▍    | 260/480 [02:38<02:25,  1.52it/s]

11/11 [==============================] - 1s 55ms/step


 54%|█████▍    | 261/480 [02:39<02:22,  1.54it/s]

13/13 [==============================] - 1s 54ms/step


 55%|█████▍    | 262/480 [02:40<02:27,  1.48it/s]

9/9 [==============================] - 0s 56ms/step


 55%|█████▍    | 263/480 [02:40<02:17,  1.58it/s]

8/8 [==============================] - 0s 56ms/step


 55%|█████▌    | 264/480 [02:41<02:07,  1.69it/s]

7/7 [==============================] - 0s 54ms/step


 55%|█████▌    | 265/480 [02:41<01:55,  1.86it/s]

9/9 [==============================] - 0s 55ms/step


 55%|█████▌    | 266/480 [02:42<01:53,  1.89it/s]

10/10 [==============================] - 1s 56ms/step


 56%|█████▌    | 267/480 [02:42<01:56,  1.83it/s]

13/13 [==============================] - 1s 55ms/step


 56%|█████▌    | 268/480 [02:43<02:10,  1.63it/s]

13/13 [==============================] - 1s 55ms/step


 56%|█████▌    | 269/480 [02:44<02:17,  1.53it/s]

11/11 [==============================] - 1s 54ms/step


 56%|█████▋    | 270/480 [02:44<02:15,  1.55it/s]

9/9 [==============================] - 0s 55ms/step


 56%|█████▋    | 271/480 [02:45<02:08,  1.63it/s]

7/7 [==============================] - 0s 54ms/step


 57%|█████▋    | 272/480 [02:45<01:55,  1.80it/s]

9/9 [==============================] - 0s 55ms/step


 57%|█████▋    | 273/480 [02:46<01:54,  1.81it/s]

10/10 [==============================] - 1s 55ms/step


 57%|█████▋    | 274/480 [02:46<01:56,  1.76it/s]

16/16 [==============================] - 1s 55ms/step


 57%|█████▋    | 275/480 [02:47<02:19,  1.47it/s]

14/14 [==============================] - 1s 54ms/step


 57%|█████▊    | 276/480 [02:48<02:25,  1.40it/s]

14/14 [==============================] - 1s 56ms/step


 58%|█████▊    | 277/480 [02:49<02:32,  1.33it/s]

17/17 [==============================] - 1s 55ms/step


 58%|█████▊    | 278/480 [02:50<02:46,  1.21it/s]

18/18 [==============================] - 1s 57ms/step


 58%|█████▊    | 279/480 [02:51<03:02,  1.10it/s]

21/21 [==============================] - 1s 57ms/step


 58%|█████▊    | 280/480 [02:52<03:23,  1.02s/it]

17/17 [==============================] - 1s 56ms/step


 59%|█████▊    | 281/480 [02:53<03:23,  1.02s/it]

12/12 [==============================] - 1s 55ms/step


 59%|█████▉    | 282/480 [02:54<03:04,  1.07it/s]

9/9 [==============================] - 0s 57ms/step


 59%|█████▉    | 283/480 [02:55<02:39,  1.23it/s]

10/10 [==============================] - 1s 56ms/step


 59%|█████▉    | 284/480 [02:55<02:27,  1.33it/s]

10/10 [==============================] - 1s 56ms/step


 59%|█████▉    | 285/480 [02:56<02:18,  1.41it/s]

12/12 [==============================] - 1s 56ms/step


 60%|█████▉    | 286/480 [02:57<02:17,  1.41it/s]

12/12 [==============================] - 1s 54ms/step


 60%|█████▉    | 287/480 [02:57<02:15,  1.43it/s]

10/10 [==============================] - 1s 57ms/step


 60%|██████    | 288/480 [02:58<02:09,  1.48it/s]

12/12 [==============================] - 1s 54ms/step


 60%|██████    | 289/480 [02:59<02:11,  1.46it/s]

10/10 [==============================] - 1s 55ms/step


 60%|██████    | 290/480 [02:59<02:06,  1.50it/s]

10/10 [==============================] - 1s 57ms/step


 61%|██████    | 291/480 [03:00<02:01,  1.56it/s]

11/11 [==============================] - 1s 56ms/step


 61%|██████    | 292/480 [03:00<02:02,  1.53it/s]

10/10 [==============================] - 1s 56ms/step


 61%|██████    | 293/480 [03:01<02:00,  1.56it/s]

11/11 [==============================] - 1s 57ms/step


 61%|██████▏   | 294/480 [03:02<01:59,  1.55it/s]

11/11 [==============================] - 1s 55ms/step


 61%|██████▏   | 295/480 [03:02<01:58,  1.56it/s]

11/11 [==============================] - 1s 56ms/step


 62%|██████▏   | 296/480 [03:03<01:58,  1.56it/s]

11/11 [==============================] - 1s 58ms/step


 62%|██████▏   | 297/480 [03:04<02:00,  1.52it/s]

9/9 [==============================] - 0s 56ms/step


 62%|██████▏   | 298/480 [03:04<01:54,  1.60it/s]

9/9 [==============================] - 0s 57ms/step


 62%|██████▏   | 299/480 [03:05<01:48,  1.66it/s]

10/10 [==============================] - 1s 56ms/step


 62%|██████▎   | 300/480 [03:05<01:49,  1.65it/s]

9/9 [==============================] - 0s 55ms/step


 63%|██████▎   | 301/480 [03:06<01:43,  1.72it/s]

10/10 [==============================] - 1s 57ms/step


 63%|██████▎   | 302/480 [03:07<01:45,  1.69it/s]

10/10 [==============================] - 1s 57ms/step


 63%|██████▎   | 303/480 [03:07<01:45,  1.67it/s]

11/11 [==============================] - 1s 56ms/step


 63%|██████▎   | 304/480 [03:08<01:48,  1.62it/s]

12/12 [==============================] - 1s 57ms/step


 64%|██████▎   | 305/480 [03:09<01:53,  1.55it/s]

10/10 [==============================] - 1s 56ms/step


 64%|██████▍   | 306/480 [03:09<01:49,  1.59it/s]

9/9 [==============================] - 0s 59ms/step


 64%|██████▍   | 307/480 [03:10<01:46,  1.63it/s]

10/10 [==============================] - 1s 57ms/step


 64%|██████▍   | 308/480 [03:10<01:45,  1.62it/s]

11/11 [==============================] - 1s 58ms/step


 64%|██████▍   | 309/480 [03:11<01:48,  1.57it/s]

11/11 [==============================] - 1s 57ms/step


 65%|██████▍   | 310/480 [03:12<01:50,  1.53it/s]

8/8 [==============================] - 0s 58ms/step


 65%|██████▍   | 311/480 [03:12<01:42,  1.66it/s]

11/11 [==============================] - 1s 55ms/step


 65%|██████▌   | 312/480 [03:13<01:44,  1.61it/s]

9/9 [==============================] - 0s 55ms/step


 65%|██████▌   | 313/480 [03:13<01:40,  1.67it/s]

9/9 [==============================] - 0s 56ms/step


 65%|██████▌   | 314/480 [03:14<01:36,  1.73it/s]

12/12 [==============================] - 1s 56ms/step


 66%|██████▌   | 315/480 [03:15<01:42,  1.61it/s]

13/13 [==============================] - 1s 56ms/step


 66%|██████▌   | 316/480 [03:15<01:48,  1.51it/s]

12/12 [==============================] - 1s 57ms/step


 66%|██████▌   | 317/480 [03:16<01:50,  1.47it/s]

7/7 [==============================] - 0s 58ms/step


 66%|██████▋   | 318/480 [03:17<01:39,  1.63it/s]

10/10 [==============================] - 1s 56ms/step


 66%|██████▋   | 319/480 [03:17<01:36,  1.66it/s]

10/10 [==============================] - 1s 57ms/step


 67%|██████▋   | 320/480 [03:18<01:36,  1.65it/s]

9/9 [==============================] - 0s 56ms/step


 67%|██████▋   | 321/480 [03:18<01:32,  1.73it/s]

10/10 [==============================] - 1s 56ms/step


 67%|██████▋   | 322/480 [03:19<01:32,  1.71it/s]

9/9 [==============================] - 0s 57ms/step


 67%|██████▋   | 323/480 [03:19<01:28,  1.77it/s]

11/11 [==============================] - 1s 57ms/step


 68%|██████▊   | 324/480 [03:20<01:33,  1.67it/s]

10/10 [==============================] - 1s 58ms/step


 68%|██████▊   | 325/480 [03:21<01:32,  1.68it/s]

10/10 [==============================] - 1s 56ms/step


 68%|██████▊   | 326/480 [03:21<01:31,  1.68it/s]

11/11 [==============================] - 1s 58ms/step


 68%|██████▊   | 327/480 [03:22<01:35,  1.60it/s]

12/12 [==============================] - 1s 55ms/step


 68%|██████▊   | 328/480 [03:23<01:39,  1.53it/s]

8/8 [==============================] - 0s 58ms/step


 69%|██████▊   | 329/480 [03:23<01:32,  1.63it/s]

9/9 [==============================] - 0s 56ms/step


 69%|██████▉   | 330/480 [03:24<01:29,  1.68it/s]

9/9 [==============================] - 0s 58ms/step


 69%|██████▉   | 331/480 [03:24<01:28,  1.69it/s]

9/9 [==============================] - 0s 57ms/step


 69%|██████▉   | 332/480 [03:25<01:25,  1.73it/s]

10/10 [==============================] - 1s 58ms/step


 69%|██████▉   | 333/480 [03:25<01:26,  1.70it/s]

10/10 [==============================] - 1s 58ms/step


 70%|██████▉   | 334/480 [03:26<01:26,  1.70it/s]

13/13 [==============================] - 1s 57ms/step


 70%|██████▉   | 335/480 [03:27<01:34,  1.53it/s]

10/10 [==============================] - 1s 57ms/step


 70%|███████   | 336/480 [03:27<01:32,  1.56it/s]

9/9 [==============================] - 0s 57ms/step


 70%|███████   | 337/480 [03:28<01:27,  1.64it/s]

9/9 [==============================] - 0s 57ms/step


 70%|███████   | 338/480 [03:29<01:23,  1.71it/s]

16/16 [==============================] - 1s 57ms/step


 71%|███████   | 339/480 [03:30<01:38,  1.43it/s]

10/10 [==============================] - 1s 56ms/step


 71%|███████   | 340/480 [03:30<01:33,  1.49it/s]

10/10 [==============================] - 1s 58ms/step


 71%|███████   | 341/480 [03:31<01:31,  1.52it/s]

9/9 [==============================] - 0s 56ms/step


 71%|███████▏  | 342/480 [03:31<01:26,  1.59it/s]

11/11 [==============================] - 1s 57ms/step


 71%|███████▏  | 343/480 [03:32<01:27,  1.57it/s]

13/13 [==============================] - 1s 57ms/step


 72%|███████▏  | 344/480 [03:33<01:31,  1.48it/s]

16/16 [==============================] - 1s 56ms/step


 72%|███████▏  | 345/480 [03:34<01:43,  1.30it/s]

10/10 [==============================] - 1s 56ms/step


 72%|███████▏  | 346/480 [03:34<01:35,  1.41it/s]

9/9 [==============================] - 0s 57ms/step


 72%|███████▏  | 347/480 [03:35<01:27,  1.52it/s]

10/10 [==============================] - 1s 56ms/step


 72%|███████▎  | 348/480 [03:35<01:24,  1.57it/s]

10/10 [==============================] - 1s 57ms/step


 73%|███████▎  | 349/480 [03:36<01:22,  1.58it/s]

10/10 [==============================] - 1s 57ms/step


 73%|███████▎  | 350/480 [03:37<01:22,  1.58it/s]

10/10 [==============================] - 1s 56ms/step


 73%|███████▎  | 351/480 [03:37<01:19,  1.61it/s]

10/10 [==============================] - 1s 58ms/step


 73%|███████▎  | 352/480 [03:38<01:19,  1.61it/s]

9/9 [==============================] - 0s 57ms/step


 74%|███████▎  | 353/480 [03:38<01:16,  1.65it/s]

12/12 [==============================] - 1s 56ms/step


 74%|███████▍  | 354/480 [03:39<01:20,  1.56it/s]

11/11 [==============================] - 1s 55ms/step


 74%|███████▍  | 355/480 [03:40<01:20,  1.55it/s]

8/8 [==============================] - 0s 54ms/step


 74%|███████▍  | 356/480 [03:40<01:14,  1.68it/s]

9/9 [==============================] - 0s 56ms/step


 74%|███████▍  | 357/480 [03:41<01:11,  1.71it/s]

8/8 [==============================] - 0s 57ms/step


 75%|███████▍  | 358/480 [03:41<01:08,  1.79it/s]

10/10 [==============================] - 1s 55ms/step


 75%|███████▍  | 359/480 [03:42<01:09,  1.74it/s]

8/8 [==============================] - 0s 57ms/step


 75%|███████▌  | 360/480 [03:42<01:06,  1.80it/s]

12/12 [==============================] - 1s 56ms/step


 75%|███████▌  | 361/480 [03:43<01:12,  1.64it/s]

10/10 [==============================] - 1s 57ms/step


 75%|███████▌  | 362/480 [03:44<01:12,  1.63it/s]

9/9 [==============================] - 0s 57ms/step


 76%|███████▌  | 363/480 [03:44<01:09,  1.69it/s]

7/7 [==============================] - 0s 54ms/step


 76%|███████▌  | 364/480 [03:45<01:02,  1.86it/s]

9/9 [==============================] - 0s 54ms/step


 76%|███████▌  | 365/480 [03:45<01:01,  1.86it/s]

12/12 [==============================] - 1s 56ms/step


 76%|███████▋  | 366/480 [03:46<01:06,  1.72it/s]

9/9 [==============================] - 0s 56ms/step


 76%|███████▋  | 367/480 [03:47<01:05,  1.73it/s]

10/10 [==============================] - 1s 57ms/step


 77%|███████▋  | 368/480 [03:47<01:06,  1.69it/s]

8/8 [==============================] - 0s 56ms/step


 77%|███████▋  | 369/480 [03:48<01:02,  1.78it/s]

9/9 [==============================] - 0s 55ms/step


 77%|███████▋  | 370/480 [03:48<01:00,  1.83it/s]

11/11 [==============================] - 1s 56ms/step


 77%|███████▋  | 371/480 [03:49<01:03,  1.73it/s]

10/10 [==============================] - 1s 56ms/step


 78%|███████▊  | 372/480 [03:49<01:03,  1.70it/s]

9/9 [==============================] - 0s 57ms/step


 78%|███████▊  | 373/480 [03:50<01:01,  1.74it/s]

10/10 [==============================] - 1s 56ms/step


 78%|███████▊  | 374/480 [03:51<01:01,  1.71it/s]

10/10 [==============================] - 1s 56ms/step


 78%|███████▊  | 375/480 [03:51<01:02,  1.68it/s]

12/12 [==============================] - 1s 56ms/step


 78%|███████▊  | 376/480 [03:52<01:04,  1.60it/s]

10/10 [==============================] - 1s 56ms/step


 79%|███████▊  | 377/480 [03:53<01:03,  1.63it/s]

10/10 [==============================] - 1s 56ms/step


 79%|███████▉  | 378/480 [03:53<01:02,  1.63it/s]

11/11 [==============================] - 1s 56ms/step


 79%|███████▉  | 379/480 [03:54<01:02,  1.61it/s]

11/11 [==============================] - 1s 55ms/step


 79%|███████▉  | 380/480 [03:54<01:02,  1.61it/s]

11/11 [==============================] - 1s 56ms/step


 79%|███████▉  | 381/480 [03:55<01:03,  1.57it/s]

9/9 [==============================] - 0s 56ms/step


 80%|███████▉  | 382/480 [03:56<01:00,  1.62it/s]

8/8 [==============================] - 0s 56ms/step


 80%|███████▉  | 383/480 [03:56<00:55,  1.75it/s]

10/10 [==============================] - 1s 56ms/step


 80%|████████  | 384/480 [03:57<00:55,  1.72it/s]

10/10 [==============================] - 1s 56ms/step


 80%|████████  | 385/480 [03:57<00:55,  1.70it/s]

8/8 [==============================] - 0s 56ms/step


 80%|████████  | 386/480 [03:58<00:52,  1.79it/s]

11/11 [==============================] - 1s 57ms/step


 81%|████████  | 387/480 [03:59<00:55,  1.68it/s]

10/10 [==============================] - 1s 56ms/step


 81%|████████  | 388/480 [03:59<00:54,  1.69it/s]

10/10 [==============================] - 1s 56ms/step


 81%|████████  | 389/480 [04:00<00:54,  1.67it/s]

8/8 [==============================] - 0s 56ms/step


 81%|████████▏ | 390/480 [04:00<00:50,  1.78it/s]

11/11 [==============================] - 1s 56ms/step


 81%|████████▏ | 391/480 [04:01<00:51,  1.72it/s]

12/12 [==============================] - 1s 55ms/step


 82%|████████▏ | 392/480 [04:02<00:55,  1.60it/s]

8/8 [==============================] - 0s 57ms/step


 82%|████████▏ | 393/480 [04:02<00:51,  1.69it/s]

12/12 [==============================] - 1s 55ms/step


 82%|████████▏ | 394/480 [04:03<00:53,  1.61it/s]

10/10 [==============================] - 1s 56ms/step


 82%|████████▏ | 395/480 [04:03<00:52,  1.62it/s]

11/11 [==============================] - 1s 56ms/step


 82%|████████▎ | 396/480 [04:04<00:52,  1.60it/s]

9/9 [==============================] - 0s 56ms/step


 83%|████████▎ | 397/480 [04:05<00:50,  1.65it/s]

10/10 [==============================] - 1s 56ms/step


 83%|████████▎ | 398/480 [04:05<00:49,  1.65it/s]

11/11 [==============================] - 1s 55ms/step


 83%|████████▎ | 399/480 [04:06<00:50,  1.61it/s]

10/10 [==============================] - 1s 56ms/step


 83%|████████▎ | 400/480 [04:06<00:48,  1.63it/s]

9/9 [==============================] - 0s 55ms/step


 84%|████████▎ | 401/480 [04:07<00:46,  1.69it/s]

11/11 [==============================] - 1s 55ms/step


 84%|████████▍ | 402/480 [04:08<00:47,  1.63it/s]

6/6 [==============================] - 0s 56ms/step


 84%|████████▍ | 403/480 [04:08<00:41,  1.84it/s]

14/14 [==============================] - 1s 56ms/step


 84%|████████▍ | 404/480 [04:09<00:47,  1.59it/s]

12/12 [==============================] - 1s 56ms/step


 84%|████████▍ | 405/480 [04:10<00:48,  1.55it/s]

11/11 [==============================] - 1s 55ms/step


 85%|████████▍ | 406/480 [04:10<00:47,  1.56it/s]

12/12 [==============================] - 1s 55ms/step


 85%|████████▍ | 407/480 [04:11<00:47,  1.53it/s]

11/11 [==============================] - 1s 56ms/step


 85%|████████▌ | 408/480 [04:11<00:47,  1.52it/s]

9/9 [==============================] - 0s 57ms/step


 85%|████████▌ | 409/480 [04:12<00:44,  1.59it/s]

10/10 [==============================] - 1s 56ms/step


 85%|████████▌ | 410/480 [04:13<00:43,  1.61it/s]

9/9 [==============================] - 0s 57ms/step


 86%|████████▌ | 411/480 [04:13<00:41,  1.66it/s]

9/9 [==============================] - 0s 57ms/step


 86%|████████▌ | 412/480 [04:14<00:40,  1.68it/s]

9/9 [==============================] - 0s 56ms/step


 86%|████████▌ | 413/480 [04:14<00:38,  1.74it/s]

10/10 [==============================] - 1s 56ms/step


 86%|████████▋ | 414/480 [04:15<00:38,  1.70it/s]

4/4 [==============================] - 0s 53ms/step


 86%|████████▋ | 415/480 [04:15<00:30,  2.10it/s]

11/11 [==============================] - 1s 55ms/step


 87%|████████▋ | 416/480 [04:16<00:34,  1.88it/s]

11/11 [==============================] - 1s 56ms/step


 87%|████████▋ | 417/480 [04:16<00:36,  1.74it/s]

9/9 [==============================] - 0s 57ms/step


 87%|████████▋ | 418/480 [04:17<00:35,  1.76it/s]

12/12 [==============================] - 1s 56ms/step


 87%|████████▋ | 419/480 [04:18<00:36,  1.65it/s]

10/10 [==============================] - 1s 55ms/step


 88%|████████▊ | 420/480 [04:18<00:36,  1.66it/s]

11/11 [==============================] - 1s 55ms/step


 88%|████████▊ | 421/480 [04:19<00:36,  1.61it/s]

5/5 [==============================] - 0s 55ms/step


 88%|████████▊ | 422/480 [04:19<00:31,  1.86it/s]

9/9 [==============================] - 0s 56ms/step


 88%|████████▊ | 423/480 [04:20<00:30,  1.86it/s]

10/10 [==============================] - 1s 56ms/step


 88%|████████▊ | 424/480 [04:20<00:31,  1.81it/s]

12/12 [==============================] - 1s 55ms/step


 89%|████████▊ | 425/480 [04:21<00:32,  1.68it/s]

8/8 [==============================] - 0s 56ms/step


 89%|████████▉ | 426/480 [04:22<00:30,  1.77it/s]

13/13 [==============================] - 1s 56ms/step


 89%|████████▉ | 427/480 [04:22<00:32,  1.61it/s]

11/11 [==============================] - 1s 57ms/step


 89%|████████▉ | 428/480 [04:23<00:33,  1.56it/s]

6/6 [==============================] - 0s 58ms/step


 89%|████████▉ | 429/480 [04:23<00:28,  1.77it/s]

9/9 [==============================] - 0s 55ms/step


 90%|████████▉ | 430/480 [04:24<00:27,  1.79it/s]

10/10 [==============================] - 1s 56ms/step


 90%|████████▉ | 431/480 [04:25<00:28,  1.74it/s]

9/9 [==============================] - 0s 58ms/step


 90%|█████████ | 432/480 [04:25<00:27,  1.74it/s]

7/7 [==============================] - 0s 55ms/step


 90%|█████████ | 433/480 [04:26<00:25,  1.87it/s]

9/9 [==============================] - 0s 55ms/step


 90%|█████████ | 434/480 [04:26<00:24,  1.85it/s]

17/17 [==============================] - 1s 57ms/step


 91%|█████████ | 435/480 [04:27<00:30,  1.47it/s]

9/9 [==============================] - 0s 55ms/step


 91%|█████████ | 436/480 [04:28<00:28,  1.56it/s]

7/7 [==============================] - 0s 55ms/step


 91%|█████████ | 437/480 [04:28<00:25,  1.72it/s]

10/10 [==============================] - 1s 54ms/step


 91%|█████████▏| 438/480 [04:29<00:24,  1.72it/s]

10/10 [==============================] - 1s 54ms/step


 91%|█████████▏| 439/480 [04:29<00:24,  1.69it/s]

7/7 [==============================] - 0s 58ms/step


 92%|█████████▏| 440/480 [04:30<00:22,  1.82it/s]

10/10 [==============================] - 1s 57ms/step


 92%|█████████▏| 441/480 [04:30<00:21,  1.77it/s]

11/11 [==============================] - 1s 55ms/step


 92%|█████████▏| 442/480 [04:31<00:22,  1.72it/s]

11/11 [==============================] - 1s 55ms/step


 92%|█████████▏| 443/480 [04:32<00:22,  1.63it/s]

9/9 [==============================] - 0s 55ms/step


 92%|█████████▎| 444/480 [04:32<00:21,  1.70it/s]

5/5 [==============================] - 0s 54ms/step


 93%|█████████▎| 445/480 [04:33<00:17,  2.00it/s]

9/9 [==============================] - 0s 55ms/step


 93%|█████████▎| 446/480 [04:33<00:17,  1.97it/s]

8/8 [==============================] - 0s 57ms/step


 93%|█████████▎| 447/480 [04:34<00:16,  1.97it/s]

10/10 [==============================] - 1s 56ms/step


 93%|█████████▎| 448/480 [04:34<00:16,  1.88it/s]

11/11 [==============================] - 1s 56ms/step


 94%|█████████▎| 449/480 [04:35<00:17,  1.77it/s]

10/10 [==============================] - 1s 57ms/step


 94%|█████████▍| 450/480 [04:35<00:17,  1.74it/s]

8/8 [==============================] - 0s 55ms/step


 94%|█████████▍| 451/480 [04:36<00:15,  1.84it/s]

10/10 [==============================] - 1s 57ms/step


 94%|█████████▍| 452/480 [04:37<00:15,  1.77it/s]

10/10 [==============================] - 1s 57ms/step


 94%|█████████▍| 453/480 [04:37<00:15,  1.71it/s]

8/8 [==============================] - 0s 58ms/step


 95%|█████████▍| 454/480 [04:38<00:14,  1.80it/s]

10/10 [==============================] - 1s 56ms/step


 95%|█████████▍| 455/480 [04:38<00:14,  1.78it/s]

10/10 [==============================] - 1s 56ms/step


 95%|█████████▌| 456/480 [04:39<00:13,  1.77it/s]

14/14 [==============================] - 1s 56ms/step


 95%|█████████▌| 457/480 [04:40<00:14,  1.56it/s]

10/10 [==============================] - 1s 57ms/step


 95%|█████████▌| 458/480 [04:40<00:13,  1.60it/s]

10/10 [==============================] - 1s 56ms/step


 96%|█████████▌| 459/480 [04:41<00:12,  1.62it/s]

10/10 [==============================] - 1s 58ms/step


 96%|█████████▌| 460/480 [04:41<00:12,  1.64it/s]

10/10 [==============================] - 1s 57ms/step


 96%|█████████▌| 461/480 [04:42<00:11,  1.65it/s]

10/10 [==============================] - 1s 58ms/step


 96%|█████████▋| 462/480 [04:43<00:10,  1.65it/s]

9/9 [==============================] - 0s 55ms/step


 96%|█████████▋| 463/480 [04:43<00:10,  1.69it/s]

10/10 [==============================] - 1s 58ms/step


 97%|█████████▋| 464/480 [04:44<00:09,  1.66it/s]

10/10 [==============================] - 1s 57ms/step


 97%|█████████▋| 465/480 [04:44<00:09,  1.66it/s]

7/7 [==============================] - 0s 57ms/step


 97%|█████████▋| 466/480 [04:45<00:07,  1.82it/s]

10/10 [==============================] - 1s 57ms/step


 97%|█████████▋| 467/480 [04:45<00:07,  1.77it/s]

10/10 [==============================] - 1s 57ms/step


 98%|█████████▊| 468/480 [04:46<00:06,  1.74it/s]

9/9 [==============================] - 0s 57ms/step


 98%|█████████▊| 469/480 [04:47<00:06,  1.77it/s]

10/10 [==============================] - 1s 57ms/step


 98%|█████████▊| 470/480 [04:47<00:05,  1.75it/s]

13/13 [==============================] - 1s 56ms/step


 98%|█████████▊| 471/480 [04:48<00:05,  1.59it/s]

12/12 [==============================] - 1s 56ms/step


 98%|█████████▊| 472/480 [04:49<00:05,  1.53it/s]

9/9 [==============================] - 0s 56ms/step


 99%|█████████▊| 473/480 [04:49<00:04,  1.59it/s]

13/13 [==============================] - 1s 57ms/step


 99%|█████████▉| 474/480 [04:50<00:04,  1.48it/s]

10/10 [==============================] - 1s 57ms/step


 99%|█████████▉| 475/480 [04:51<00:03,  1.54it/s]

11/11 [==============================] - 1s 55ms/step


 99%|█████████▉| 476/480 [04:51<00:02,  1.55it/s]

9/9 [==============================] - 0s 57ms/step


 99%|█████████▉| 477/480 [04:52<00:01,  1.62it/s]

10/10 [==============================] - 1s 56ms/step


100%|█████████▉| 478/480 [04:52<00:01,  1.65it/s]

9/9 [==============================] - 0s 57ms/step


100%|█████████▉| 479/480 [04:53<00:00,  1.69it/s]

10/10 [==============================] - 1s 56ms/step


100%|██████████| 480/480 [04:53<00:00,  1.63it/s]


In [160]:
total_result

[(array([1, 2, 4, 5]), array([  3,   1, 183, 137])),
 (array([1, 2, 3, 4, 5]), array([  1,  21,   4, 312,  83])),
 (array([1, 3, 4, 5]), array([  3,   2, 104, 228])),
 (array([0, 1, 2, 3, 4, 5]), array([ 15,  17,  57, 118,  58,  84])),
 (array([0, 1, 2, 3, 4, 5]), array([ 27,  50,   3, 110,  23,  31])),
 (array([0, 1, 2, 3, 4, 5]), array([  2,   2,  41,  11, 167,  85])),
 (array([0, 1, 2, 3, 4, 5]), array([  3,   3,   7,   1, 158, 136])),
 (array([0, 1, 2, 3, 4, 5]), array([41, 88,  7, 91,  8, 56])),
 (array([0, 1, 2, 3, 4, 5]), array([  6,  65,   4,  25, 117, 127])),
 (array([0, 1, 2, 3, 4, 5]), array([  1,   6,   3,   5, 259,  50])),
 (array([1, 4, 5]), array([  1, 189, 139])),
 (array([2, 4, 5]), array([  7, 306,  70])),
 (array([0, 1, 2, 3, 4, 5]), array([  2,  54,  11,  77,  38, 131])),
 (array([4, 5]), array([102, 214])),
 (array([0, 1, 2, 3, 4, 5]), array([  6,   5,   1,  14, 255,  69])),
 (array([4, 5]), array([235, 119])),
 (array([1, 4, 5]), array([  5, 178, 155])),
 (array([

In [151]:
# i = 0
# temp = np.argmax(model.predict(np.array(test_whole[i])) , axis=1)
# cnts = np.unique(temp, return_counts=True)
c_n_t = 0
co = 0
el = 0
for i in range(len(total_result)):
    cnts = total_result[i]
    tsum = np.sum(cnts[1])
    topval = cnts[1][(np.argmax(cnts[1]))]
    
    if (cnts[1][np.argsort(cnts[1])[-1]] - cnts[1][np.argsort(cnts[1])[-2]]) / tsum > 0.4:
        # print((cnts[1][np.argsort(cnts[1])[-1]] - cnts[1][np.argsort(cnts[1])[-2]]))
        if cnts[0][(np.argmax(cnts[1]))] == test_y[i]:
            co += 1
        # print(cnts[0][(np.argmax(cnts[1]))])
        # print(test_y[i])
        # print(cnts)
    else:
        el += 1
        if cnts[0][np.argsort(cnts[1])[-2]] == test_y[i]:
            co += 1
        elif cnts[0][(np.argmax(cnts[1]))] == test_y[i]:
            co += 1
       
    c_n_t += 1

In [ ]:
444,447

In [155]:
c_n_t - el

96

In [153]:
el

384

In [152]:
co/c_n_t

0.61875

In [ ]:
np.array(total_result)[co_lst]

False

5

In [53]:
label_encoder.classes_

array(['공격적인', '긴장감', '밝은', '신나는', '우울한', '차분한'], dtype='<U4')

In [ ]:
ddddd = np.load('/content/melspectrogram_data/' + '460396'+'.npy')

In [ ]:
music = []
# for idx in tqdm(range(len(data_x))):
idx = 111
for i in range(len(data_x[idx][0])):
    if i+128 == len(data_x[idx][0]):
        break
    music.append(data_x[idx][:, i : 128 + i].reshape(128,128,-1))

In [ ]:
music = []
for i in range(len(ddddd[0])):
    if i+128 == len(ddddd[0]):
        break
    music.append(ddddd[:, i : 128 + i].reshape(128,128,-1))

In [ ]:
music = []
for i in range(len(ddddd[0])):
    if 128*(i+1) >= len(ddddd[0]):
        break
    music.append(ddddd[:, 128*i : 128 * (1+ i)].reshape(128,128,-1))

In [ ]:
result = model.predict(np.array(music))

4/4 [==============================] - 1s 257ms/step


In [ ]:
res = np.argmax(result, axis=1)

In [ ]:
np.unique(res, return_counts=True)

(array([0, 2, 3, 4, 5]), array([23, 16, 16, 27, 15]))

In [ ]:
label_encoder.classes_

array(['공격적인', '긴장감', '밝은', '신나는', '우울한', '차분한'], dtype='<U4')

In [ ]:
data_y[111]

3

In [ ]:
np.unique(rawdata['senti_tag'],return_counts=True)

(array(['불안', '슬픔', '신남', '편안해요', '행복해요', '화나요'], dtype=object),
 array([200, 200, 200, 384, 151, 202]))

In [ ]:
rawdata[620:650]

song_id                    song_name  \
620  31246870                         한(一)   
621   3628521                          4AM   
622  30689468                           결혼   
623  32183386                     Blueming   
624   3772006          Love Love Echo Song   
625  30677447  Who's Got You Singing Again   
626  32823088                    On and On   
627  30677444                      Futures   
628  31048045                   Me & You ◑   
629  31263803                    I Might ◑   
630  31263808              Feels So Good ◑   
631  32710775        눈부신 날의 고백 (Feat. 이하늘)   
632   7861355                    Don't Cry   
633  32568541           그때의 우리 (Feat. 이하늘)   
634  31742666                           나무   
635   5744594                       한강고수부지   
636  30307498                Song Of Songs   
637   5640438                   그대는 가고 없어도   
638  31014897                    Dear Moon   
639   9616627                   UFO 타고 왔니?   
640  31106985                Goodbye Seoul   
641  31367149                   Last Scene   
642   5622521             잔상 (Guitar Ver.)   
643   8170718                     널 향해 달리기   
644  31244742            Hymn of the Birds   
645  32482636                          고강동   
646   8215175                  Play Ground   
647  31564661                          물고기   
648  31063366                           잘가   
649  31352027                     햇빛처럼 빼어난   

                                            song_lyric senti_tag  
620  Do you remember you remember\nremember what yo...      행복해요  
621  일어난 건지 \n아직 잠들지 못한 건지\n당장이 내일인지 오늘인지 \n어젠지도 모르...      행복해요  
622  결혼에 대하여 \n예쁜 단어를 골라 \n예쁜 칭찬을 하고\n예쁜 밤을 만들 것\n결...      행복해요  
623  ‘뭐해?‘라는 두 글자에\n‘네가 보고 싶어’ 나의 속마음을 담아 우\n이모티콘 하...      행복해요  
624                                           No lyric      행복해요  
625  It happened so easy at the start\nGot too used...      행복해요  
626  I never thought I had a chance\nYou seemed so ...      행복해요  
627  Wind on the cool grey water \nVoices way back ...      행복해요  
628  One small step for man \none giant leap for ma...      행복해요  
629  Say hello to Tokyo\nI can see myself living ri...      행복해요  
630  Sprinkle\nMake a run for it come on\nGo\nThese...      행복해요  
631  가끔 그럴 때 있잖아\n아무도 내 편이 없는 날\n말이 안 될 것 같은 하루\n어둠...        불안  
632  세상 모든 빛이\n그대로 물들면\n작은 나의 삶은\n선물이 되죠\n내 맘 단 하나\...        불안  
633  많이 바쁜 것 같아 보여서\n잘 지내는지 더 묻지 않을게\n늘 너의 하루가 궁금한 ...        불안  
634  인사 하네요 근심없게\n나 아름다운 방식으로\n무딘 목소리와\n어설픈 자국들\n날 ...        불안  
635  왠지 가고 싶은 곳 \n거기가 어디 거기가 여기\n왠지 갖고 싶은 옷 \n그보다 좀...        불안  
636  향기로운 당신의 품에\n가만히 안겨 노래하네\n감미로운 당신의 음성\n내 귀에 울려...        불안  
637                                                 \N        불안  
638  Dear moon my moon\n가까워지지 않아\n잰 걸음으로 따라가도\n닿지 않...        불안  
639  Hello 외계인 나\n너와는 말이 통하지가 않아 허\n같은 공간 시간 함께 있는데...        불안  
640  I'll miss you \nI'll miss you\nI'll miss you\n...        불안  
641  참 오래도 버텼지 우리\n뻔히 보이는 끝을 하루씩 미루며\n더 나아지지 않을 거라\...        불안  
642  어느 순간 그림자에 비친\n내 모습은 가려진 맘 속에\n그대 품에 안겨서 어느 순간...        불안  
643  널 향해 달리기\n\n가로등도 잠들어가는\n식어가는 아스팔트 위\n운동화 끈을 고쳐...        불안  
644  You loved you loved to fly\nUp above the cloud...        불안  
645  나는 아주아주\n돈을 많이 벌어서\n고강동을 통째로\n다 사버릴 거야\n할아버지 할...        불안  
646  oh we can not respawn \nlet you someday \noh t...        불안  
647  꼭 곁에 있어줘\n끝없이 사랑해줘\n숨이 차게 너에게 잠겨 가득히\n꼭 나를 지켜줘...        불안  
648  많이 힘들었지 너 \n너에게 항상 서툴렀던 나 \n많이 힘들었지 너 \n둘이 잡은 ...        불안  
649  햇빛처럼 빼어난 사람이\n될 수 있을까\n파란 하늘과 바다를\n좋아한다고 해서\n내...        불안

In [ ]:
lst = os.listdir('/content/mfcc_data')
datam_x = []
datam_y = []
for i in tqdm(range(len(rawdata))):
   datam_x.append(np.load('/content/mfcc_data/' + str(rawdata['song_id'].iloc[i])+'.npy'))
   datam_y.append(rawdata['senti_tag'].iloc[i])

100%|██████████| 1337/1337 [00:02<00:00, 632.95it/s]


In [ ]:
datam_x[0].shape

(50, 10231)

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
datam_y = label_encoder.fit_transform(datam_y)

In [ ]:
dda = []
tt = []

# 128*128 사이즈로 멜스펙토그램 이미지를 잘라서 담아두고
# 타겟값을 같이 추가한 넘파이배열을 만든다
for idx in tqdm(range(len(datam_x))):
    for i in range(20):
        if 100 * (i+1) > len(datam_x[idx][0]):
            break
        dda.append(datam_x[idx][:, 100* i : 100 * (i+1)].reshape(50,100,1))
        tt.append(datam_y[idx])
dda = np.array(dda)
tt = np.array(tt)

100%|██████████| 1337/1337 [00:00<00:00, 35145.30it/s]


In [ ]:
dda[0].shape

(50, 256, 1)

In [ ]:
!nvidia-smi

Tue Nov 15 06:45:31 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P0    30W /  70W |  14632MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Dense, Input, BatchNormalization, Activation, Flatten

def mfcc():
    
    inputs = Input(shape=(50,100,1))
    x = Conv2D(64,3, padding='same')(inputs)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(64,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = MaxPooling2D(2)(x)
    
    x = Conv2D(128,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(128,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = MaxPooling2D(2)(x)
    
    x = Conv2D(256,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(256,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(256,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = MaxPooling2D(2)(x)
    
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = MaxPooling2D(2)(x)
    
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = Conv2D(512,3, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = MaxPooling2D(2)(x)
    
    # x = Conv2D(512,3, padding='same')(x)
    # x = BatchNormalization()(x)
    # x = Activation('relu')(x)
    # x = Conv2D(512,3, padding='same')(x)
    # x = BatchNormalization()(x)
    # x = Activation('relu')(x)
    # x = Conv2D(512,3, padding='same')(x)
    # x = BatchNormalization()(x)
    # x = Activation('relu')(x)
    # x = MaxPooling2D(2)(x)
    
    x = Flatten()(x)
    x = Dense(1024, activation='relu')(x)
    x = Dropout(0.25)(x)
    x = Dense(1024, activation='relu')(x)
    x = Dropout(0.25)(x)
    x = Dense(6, activation='softmax')(x)
    
    return tf.keras.Model(inputs, x)

In [ ]:
mfcc_model = mfcc()

In [ ]:
mfcc_model.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 50, 100, 1)]      0         
                                                                 
 conv2d_74 (Conv2D)          (None, 50, 100, 64)       640       
                                                                 
 batch_normalization_74 (Bat  (None, 50, 100, 64)      256       
 chNormalization)                                                
                                                                 
 activation_74 (Activation)  (None, 50, 100, 64)       0         
                                                                 
 conv2d_75 (Conv2D)          (None, 50, 100, 64)       36928     
                                                                 
 batch_normalization_75 (Bat  (None, 50, 100, 64)      256       
 chNormalization)                                          

In [ ]:
mfcc_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=5e-5), loss='sparse_categorical_crossentropy',  metrics=['acc'])

In [ ]:
history_ = mfcc_model.fit(dda, tt, epochs=2, batch_size=32, validation_split=0.4)

Epoch 1/2
502/502 [==============================] - 44s 89ms/step - loss: 0.1180 - acc: 0.9546 - val_loss: 3.6125 - val_acc: 0.5026
Epoch 2/2
502/502 [==============================] - 43s 85ms/step - loss: 0.1211 - acc: 0.9526 - val_loss: 4.2967 - val_acc: 0.3862


In [ ]:
mfcc_model.evaluate(dda, tt)

836/836 [==============================] - 18s 22ms/step - loss: 1.8442 - acc: 0.7092


[1.8442332744598389, 0.7091622948646545]